"""Fallback flag URLs for national teams when SStats has no logoUrl."""
from __future__ import annotations

from typing import Optional

# ISO 3166-1 codes supported by flagcdn.com (incl. gb-eng, gb-sct, gb-wls).
NATIONAL_TEAM_FLAG_CODES: dict[str, str] = {
    "Argentina": "ar",
    "Australia": "au",
    "Belgium": "be",
    "Bosnia and Herzegovina": "ba",
    "Bosnia & Herzegovina": "ba",
    "Brazil": "br",
    "Canada": "ca",
    "Cameroon": "cm",
    "Chile": "cl",
    "Colombia": "co",
    "Costa Rica": "cr",
    "Croatia": "hr",
    "Czech Republic": "cz",
    "Denmark": "dk",
    "Ecuador": "ec",
    "England": "gb-eng",
    "France": "fr",
    "Germany": "de",
    "Ghana": "gh",
    "Haiti": "ht",
    "Iran": "ir",
    "Italy": "it",
    "Japan": "jp",
    "Mexico": "mx",
    "Morocco": "ma",
    "Netherlands": "nl",
    "New Zealand": "nz",
    "Nigeria": "ng",
    "Panama": "pa",
    "Paraguay": "py",
    "Peru": "pe",
    "Poland": "pl",
    "Portugal": "pt",
    "Qatar": "qa",
    "Romania": "ro",
    "Russia": "ru",
    "Saudi Arabia": "sa",
    "Scotland": "gb-sct",
    "Senegal": "sn",
    "Serbia": "rs",
    "Slovakia": "sk",
    "South Africa": "za",
    "South Korea": "kr",
    "Korea Republic": "kr",
    "Spain": "es",
    "Switzerland": "ch",
    "Tunisia": "tn",
    "Turkey": "tr",
    "Türkiye": "tr",
    "Ukraine": "ua",
    "United States": "us",
    "USA": "us",
    "Uruguay": "uy",
    "Venezuela": "ve",
    "Wales": "gb-wls",
    "Egypt": "eg",
    "Austria": "at",
    "Norway": "no",
    "Congo DR": "cd",
    "Algeria": "dz",
    "Cape Verde": "cv",
    "Cape Verde Islands": "cv",
    "Jordan": "jo",
    "Iraq": "iq",
    "Uzbekistan": "uz",
    "Greece": "gr",
    "Slovenia": "si",
    "Hungary": "hu",
    "Albania": "al",
    "Georgia": "ge",
    "Finland": "fi",
    "Iceland": "is",
    "Northern Ireland": "gb-nir",
    "Republic of Ireland": "ie",
    "Ireland": "ie",
    "China": "cn",
    "Syria": "sy",
    "Oman": "om",
    "Bahrain": "bh",
    "Palestine": "ps",
    "Kyrgyzstan": "kg",
    "Tajikistan": "tj",
    "Thailand": "th",
    "Vietnam": "vn",
    "North Korea": "kp",
    "India": "in",
    "Curaçao": "cw",
    "Curacao": "cw",
    "Ivory Coast": "ci",
    "Côte d'Ivoire": "ci",
    "Sweden": "se",
}


def national_flag_url(name_en: Optional[str]) -> Optional[str]:
    if not name_en:
        return None
    code = NATIONAL_TEAM_FLAG_CODES.get(name_en.strip())
    if not code:
        return None
    return f"https://flagcdn.com/w40/{code}.png"
